Shop/Controllers/CartController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity.UI.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.WebUtilities;
using Microsoft.EntityFrameworkCore;
using Shop.Data;
using Shop.Models;
using Shop.Models.ViewModels;
using Shop.Services;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Security.Claims;
using System.Text;
using System.Text.Encodings.Web;
using System.Threading.Tasks;

namespace Shop.Controllers
{
    [Authorize]
    public class CartController : Controller
    {
        private readonly ApplicationDbContext _db;
        private readonly IEmailSender _emailSender;
        private readonly IWebHostEnvironment _webHostEnvironment;
        public CartController(ApplicationDbContext db, IEmailSender emailSender, IWebHostEnvironment webHostEnvironment)
        {
            _db = db;
            _emailSender = emailSender;
            _webHostEnvironment = webHostEnvironment;
        }
        public IActionResult Index()
        {
            List<ShoppingCart> shoppingCartList = new List<ShoppingCart>();
            if (HttpContext.Session.Get<IEnumerable<ShoppingCart>>(ENV.SessionCard) != null &&
                HttpContext.Session.Get<IEnumerable<ShoppingCart>>(ENV.SessionCard).Count() > 0)
            {
                shoppingCartList = HttpContext.Session.Get<List<ShoppingCart>>(ENV.SessionCard);
            }
            List<Product> products = new List<Product>();
            foreach (var item in shoppingCartList)
            {
                Product product = _db.Products.Include(u => u.Category).FirstOrDefault(i => i.Id == item.ProductId);
                products.Add(product);
            }
            return View(products);
        }

        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //[ActionName("Index")]
        //public IActionResult IndexPost()
        //{
        //    return RedirectToAction(nameof(Order));
        //}

        public IActionResult RemoveFromCart(int id)
        {
            List<ShoppingCart> shoppingCartList = new List<ShoppingCart>();
            if (HttpContext.Session.Get<IEnumerable<ShoppingCart>>(ENV.SessionCard) != null &&
                HttpContext.Session.Get<IEnumerable<ShoppingCart>>(ENV.SessionCard).Count() > 0)
            {
                shoppingCartList = HttpContext.Session.Get<List<ShoppingCart>>(ENV.SessionCard);
            }

            var removeItem = shoppingCartList.SingleOrDefault(u => u.ProductId == id);
            if (removeItem != null)
            {
                shoppingCartList.Remove(removeItem);
            }

            HttpContext.Session.Set(ENV.SessionCard, shoppingCartList);
            return RedirectToAction("Index");
        }

        public IActionResult Details(int id)
        {
            List<ShoppingCart> shoppingCartList = new List<ShoppingCart>();
            if (HttpContext.Session.Get<IEnumerable<ShoppingCart>>(ENV.SessionCard) != null &&
                HttpContext.Session.Get<IEnumerable<ShoppingCart>>(ENV.SessionCard).Count() > 0)
            {
                shoppingCartList = HttpContext.Session.Get<List<ShoppingCart>>(ENV.SessionCard);
            }

            DetailsVM vm = new DetailsVM()
            {
                Product = _db.Products.Include(u => u.Category).FirstOrDefault(i => i.Id == id),
                InCard = false,
            };

            foreach (var item in shoppingCartList)
            {
                if (item.ProductId == id)
                {
                    vm.InCard = true;
                }
            }

            return View(vm);
        }

        public IActionResult Order()
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claimSession = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);

            List<ShoppingCart> shoppingCartList = new List<ShoppingCart>();
            if (HttpContext.Session.Get<IEnumerable<ShoppingCart>>(ENV.SessionCard) != null &&
                HttpContext.Session.Get<IEnumerable<ShoppingCart>>(ENV.SessionCard).Count() > 0)
            {
                shoppingCartList = HttpContext.Session.Get<List<ShoppingCart>>(ENV.SessionCard);
            }
            List<Product> products = new List<Product>();
            foreach (var item in shoppingCartList)
            {
                Product product = _db.Products.Include(u => u.Category).FirstOrDefault(i => i.Id == item.ProductId);
                products.Add(product);
            }

            ProductUserVM productUserVM = new ProductUserVM()
            {
                ProductList = products,
                AppUser = _db.AppUser.FirstOrDefault(i => i.Id == claimSession.Value),
            };
            return View(productUserVM);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [ActionName("Order")]
        public async Task<IActionResult> OrderPostAsync(ProductUserVM productUserVM)
        {
            // send email

            var path_template = _webHostEnvironment.WebRootPath + Path.DirectorySeparatorChar.ToString()
                + "teplates" + Path.DirectorySeparatorChar.ToString() + "orderproduct_template.html";

            var subject = "New order";
            string HTML_body = "";

            using (StreamReader sr = System.IO.File.OpenText(path_template))
            {
                HTML_body = sr.ReadToEnd();
            }

            StringBuilder productsSB = new StringBuilder();

            foreach (var item in productUserVM.ProductList)
            {
                productsSB.Append($"{item.Name}\t | \t{item.Price}$UAN");
            }

            string messageBody = string.Format(
                HTML_body,
                productUserVM.AppUser.Name, productUserVM.AppUser.Email, productUserVM.AppUser.PhoneNumber,
                productsSB.ToString());


            await _emailSender.SendEmailAsync(ENV.AdminEmail, subject, messageBody);

            return RedirectToAction(nameof(OrderConfirmarion));

        }

        public IActionResult OrderConfirmarion()
        {
            HttpContext.Session.Clear();
            return View();
        }
    }
}

Shop/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Shop.Data;
using Shop.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace Shop.Controllers
{
    public class CategoryController : Controller
    {

        private readonly ApplicationDbContext _db;
        private readonly IWebHostEnvironment _webHostEnvironment;
        public CategoryController(ApplicationDbContext db, IWebHostEnvironment webHostEnvironment)
        {
            this._db = db;
            this._webHostEnvironment = webHostEnvironment;
        }
        public IActionResult Index()
        {
            IEnumerable<Category> categories = _db.Category;
            return View(categories);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Category category)
        {
            if (ModelState.IsValid)
            {
                _db.Category.Add(category);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View();
        }

        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var category = _db.Category.Find(id);
            if (category == null)
            {
                return NotFound();
            }
            return View(category);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePost(int? id)
        {
            var category = _db.Category.Find(id);
            if (category == null)
            {
                return NotFound();
            }

            var products = _db.Products.Where(w => w.CategoryId == category.Id);

            string webRootPath = _webHostEnvironment.WebRootPath;
            string uploads = webRootPath + ENV.imagepass;

            foreach (var item in products)
            {
                string path = Path.Combine(uploads, item.Image);
                if (item.Image != "null.png")
                {
                    if (System.IO.File.Exists(path))
                    {
                        System.IO.File.Delete(path);
                    }
                }
            }

            _db.Products.RemoveRange(products);

            _db.Category.Remove(category);
            _db.SaveChanges();

            return RedirectToAction("Index");
        }

        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var category = _db.Category.Find(id);
            if (category == null)
            {
                return NotFound();
            }
            return View(category);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult EditPost(Category category)
        {
            if (ModelState.IsValid)
            {
                _db.Category.Update(category);
                _db.SaveChanges(); 
                return RedirectToAction("Index");
            }
            return View(category);
        }
    }
}

Shop/Controllers/ProductsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Shop.Data;
using Shop.Models;
using Shop.Models.ViewModels;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace Shop.Controllers
{
    public class ProductsController : Controller
    {
        private readonly ApplicationDbContext _db;
        private readonly IWebHostEnvironment _webHostEnvironment;
        public ProductsController(ApplicationDbContext db, IWebHostEnvironment webHostEnvironment)
        {
            this._db = db;
            this._webHostEnvironment = webHostEnvironment;
        }

        public IActionResult Index()
        {
            IEnumerable<Product> products = _db.Products.Include(u => u.Category);
            return View(products);
        }

        [Authorize]
        public IActionResult Upsert(int? id)
        {
            ProductVM productvm = new ProductVM()
            {
                Product = new Product(),
                CategorySelectList = _db.Category.Select(u => new SelectListItem() { Text = u.Name, Value = u.Id.ToString() }),
            };
            if (id == null)
            {
                return View(productvm);
            }
            else
            {
                productvm.Product = _db.Products.Find(id);
                if (productvm.Product == null)
                {
                    return NotFound();
                }
                return View(productvm);
            }
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Upsert(ProductVM productVM)
        {
            if (ModelState.IsValid)
            {
                var files = HttpContext.Request.Form.Files;
                string webRootPath = _webHostEnvironment.WebRootPath;

                string uploads = webRootPath + ENV.imagepass;
                string FileName = Guid.NewGuid().ToString();
                string FileExt = ".png";
                if (files.Count > 0)
                {
                    FileExt = Path.GetExtension(files[0].FileName);
                }

                if (productVM.Product.Id == 0)
                {
                    if (files.Count > 0)
                    {
                        using (var fs = new FileStream(Path.Combine(uploads, FileName + FileExt), FileMode.Create))
                        {
                            files[0].CopyTo(fs);
                        }
                        productVM.Product.Image = FileName + FileExt;
                    }
                    else
                    {
                        productVM.Product.Image = "null" + FileExt;
                    }
                    _db.Products.Add(productVM.Product);
                }
                else
                {
                    var formObj = _db.Products.AsNoTracking().FirstOrDefault(u => u.Id == productVM.Product.Id);
                    if (files.Count > 0)
                    {
                        var oldFile = Path.Combine(uploads, formObj.Image);
                        if (System.IO.File.Exists(oldFile))
                        {
                            System.IO.File.Delete(oldFile);
                        }
                        using (var fs = new FileStream(Path.Combine(uploads, FileName + FileExt), FileMode.Create))
                        {
                            files[0].CopyTo(fs);
                        }
                        productVM.Product.Image = FileName + FileExt;
                    }
                    else
                    {
                        productVM.Product.Image = "null.jpg";
                    }
                    _db.Products.Update(productVM.Product);
                }
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            productVM.CategorySelectList = _db.Category.Select(s => new SelectListItem
            {
                Text = s.Name,
                Value = s.Id.ToString()
            });
            return View(productVM);
        }

        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var products = _db.Products.Find(id);
            if (products == null)
            {
                return NotFound();
            }
            return View(products);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePost(int? id)
        {
            var products = _db.Products.Find(id);
            if (products == null)
            {
                return NotFound();
            }
            string webRootPath = _webHostEnvironment.WebRootPath;
            string uploads = webRootPath + ENV.imagepass;
            string path = Path.Combine(uploads, products.Image);

            if (products.Image != "null.png")
            {
                if (System.IO.File.Exists(path))
                {
                    System.IO.File.Delete(path);
                }
            }

            _db.Products.Remove(products);
            _db.SaveChanges();

            return RedirectToAction("Index");
        }

    }
}

Shop/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] Shop15</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" integrity="sha512-iBBXm8fW90+nuLcSKlbmrPcLa0OT92xO1BIsZ+ywDWZCvqsWgccV3gFoRBv0z+8dLJgyAHIhR35VZc2oM/gI1w==" crossorigin="anonymous" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="~/css/Colors.css" rel="stylesheet" />
</head>
<body>
    <header class="hiddenable">
        <nav class="navbar navbar-expand-lg navbar-dark bs-dark" style="padding: .6rem 0;">
            <partial name="_header" />
        </nav>
    </header>
     @RenderBody()

    <footer class="footer txt-light item-font bs-dark">
        <div class="container text-center" style="font-size: 1.1rem">
            Shop15 - 2021
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Shop/Views/Shared/_cartProduct.cshtml
@model Shop.Models.Product;

<style>
    .img-card {
        background-size: cover;
        max-width: 222px;
        max-height: 206px;
    }

    .card-template-hover h6 {
        transition: .2s;
    }

    .card-template-hover:hover h6 {
        color: #56cc9d;
    }

    .bordered {
        border-bottom: 2px solid #6cc3d5;
        transition: .2s;
    }

        .bordered:hover {
            border-bottom: 2px double #56cc9d;
        }

    .btneffect:hover {
        color: white;
    }

    .hovered:hover {
        transform: scale(1.040);
    }
</style>
<div class="card bs-dark-light1 rounded prices bordered hovered filter @Model.Category.Name" style="max-width: 226px;">
    <a asp-controller="Cart" asp-action="Details" asp-route-id="@Model.Id" class="text-decoration-none bg-white rounded card-img-top d-flex align-items-center" style="width: 222px; height: 206px;">
        <img src="~/Images/Products/@Model.Image" class="img-card rounded" alt="...">
    </a>
    <div class="card-body p-3">
        <a asp-controller="Cart" asp-action="Details" asp-route-id="@Model.Id" class="card-template-hover text-decoration-none"><h6 class="txt-light head-font">@Model.Name</h6></a>
    </div>
    <div class="p-3">
        <div class="d-flex">
            <h3 class="item-font txt-warning priceitem">@Model.Price <i class="fas fa-hryvnia"></i></h3>
            <h5 class="item-font txt-danger align-self-end ml-2">uan</h5>
        </div>
        <div class="mt-2">
            @if (Model.Category.ShowOrder > 20)
            {
                <p class="txt-successfull item-font mb-0"><i class="fas fa-dolly"></i> Avaible</p>
            }
            else
            {
                <p class="txt-danger item-font mb-0"><i class="fas fa-dolly"></i> Ending</p>
            }
        </div>
    </div>
    <div class="card-footer p-0 pb-1">
        <div class="d-flex p-0 justify-content-center">
            <a class="p-2 text-center bg-transparent txt-successfull rounded-0 item-font btneffect" asp-route-Id="@Model.Id" asp-action="RemoveFromCart"><i class="fas fa-trash"></i></a>           
        </div>
    </div>
</div>

Shop/Views/Shared/_categoryCard.cshtml
@model Shop.Models.Category;

<style>
    .card-template-hover h6 {
        transition: .2s;
    }

    .card-template-hover:hover h6 {
        color: #56cc9d;
    }

    .bordered {
        border-bottom: 2px solid #6cc3d5;
        transition: .2s;
    }

        .bordered:hover {
            border-bottom: 2px double #56cc9d;
        }

    .btneffect:hover {
        color: white;
    }

    .hovered:hover {
        transform: scale(1.040);
    }
</style>
<div class="card bs-dark-light1 rounded prices bordered hovered" style="width: 226px;">
    <div class="card-body p-3">
        <a asp-controller="Home" asp-action="Details" asp-route-id="@Model.Id" class="card-template-hover text-decoration-none text-center"><h5 class="txt-light head-font">@Model.Name</h5></a>
    </div>
    <div class="p-3">
        <div class="d-flex justify-content-center">
            <h3 class="head-font txt-warning priceitem">@Model.ShowOrder <i class="fas fa-dolly"></i></h3>
        </div>
    </div>
    @if (User.IsInRole(ENV.AdminRole))
    {
        <div class="card-footer p-0 pb-1">
            <div class="d-flex p-0">
                <a class="p-2 text-center bg-transparent txt-successfull rounded-0 item-font btneffect" style="width: 50%;" asp-route-Id="@Model.Id" asp-action="Edit"><i class="fas fa-edit"></i></a>
                <a class="p-2 text-center bg-transparent txt-danger rounded-0 item-font btneffect" style="width: 50%;" asp-route-Id="@Model.Id" asp-action="Delete"><i class="fas fa-trash"></i></a>
            </div>
        </div>
    }
</div>

Shop/Views/Shared/_header.cshtml
@using Microsoft.AspNetCore.Http;
@inject IHttpContextAccessor HttpContextAccessor;
@using Shop.Services;


<div class="container">
    <a class="navbar-brand head-font" style="font-size: 22px;" asp-controller="Home" asp-action="Index">Shop15</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav flex-grow-1">
            <li class="nav-item">
                <a class="nav-link item-font" asp-area="" asp-controller="Home" asp-action="Index"><i class="fas fa-home" style="font-size: 18px;"></i> Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link item-font" asp-area="" asp-controller="Category" asp-action="Index"><i class="fas fa-list-ul" style="font-size: 18px;"></i> Category</a>
            </li>
            <li class="nav-item">
                <a class="nav-link item-font" asp-area="" asp-controller="Products" asp-action="Index"><i class="fas fa-mobile" style="font-size: 18px;"></i> Device</a>
            </li>
            <li class="nav-item">
                @if (HttpContextAccessor.HttpContext.Session.Get<List<ShoppingCart>>(ENV.SessionCard) != null)
                {
                    <a class="nav-link item-font" asp-area="" asp-controller="Cart" asp-action="Index">
                        @{
                            var count = HttpContextAccessor.HttpContext.Session.Get<List<ShoppingCart>>(ENV.SessionCard).Count();
                        }
                        <i class="fas fa-shopping-cart"></i> Cart (@count)
                    </a>
                }
                else
                {
                    <a asp-controller="Cart" asp-action="Index" class="nav-link item-font"><i class="fas fa-shopping-cart"></i> Cart (0)</a>
                }
            </li>
            <li class="nav-item ml-auto">
                <partial name="_LoginPartial" />
            </li>
            @if (User.IsInRole(ENV.AdminRole))
            {
                <li class="nav-item">
                    <a class="nav-link item-font" asp-area="Identity" asp-page="/Account/Register"> Create Admin</a>
                </li>
            }
        </ul>
    </div>
</div>

Shop/Views/Shared/_productCard.cshtml
@model Shop.Models.Product;

<style>
    .img-card {
        background-size: cover;
        max-width: 222px;
        max-height: 206px;
    }

    .card-template-hover h6 {
        transition: .2s;
    }

    .card-template-hover:hover h6 {
        color: #56cc9d;
        text-decoration:underline;
    }

    .bordered {
        border-bottom: 2px solid #6cc3d5;
        transition: .2s;
    }

        .bordered:hover {
            border-bottom: 2px solid #56cc9d;
        }
    .hovered:hover {
        transform: scale(1.040);
    }
</style>
<div class="card bs-dark-light1 rounded bordered filter hovered @Model.Category.Name" style="max-width: 226px;">
    <a asp-controller="Home" asp-action="Details" asp-route-id="@Model.Id" class="text-decoration-none bg-white rounded card-img-top d-flex align-items-center" style="width: 222px; height: 206px;">
        <img src="~/Images/Products/@Model.Image" class="img-card rounded" alt="...">
    </a>
    <div class="card-body p-3">
        <a asp-controller="Home" asp-action="Details" asp-route-id="@Model.Id" class="card-template-hover text-decoration-none"><h6 class="txt-light head-font">@Model.Name</h6></a>
    </div>
    <div class="p-3">
        <div class="d-flex">
            <h3 class="item-font txt-info">@Model.Price <i class="fas fa-hryvnia"></i></h3>
            <h5 class="item-font txt-danger align-self-end ml-2">uan</h5>
        </div>
        <div class="mt-2">
            @if (Model.Category.ShowOrder > 20)
            {
                <p class="txt-successfull item-font"><i class="fas fa-dolly"></i> Avaible</p>
            }
            else
            {
                <p class="txt-danger item-font"><i class="fas fa-dolly"></i> Ending</p>
            }
        </div>
    </div>
    @if (User.IsInRole(ENV.AdminRole))
    {
        <div class="card-footer p-0 pb-1">
            <div class="d-flex p-0">
                <a class="p-2 text-center bg-transparent txt-successfull rounded-0 item-font btneffect" style="width: 50%;" asp-route-Id="@Model.Id" asp-action="Upsert"><i class="fas fa-edit"></i></a>
                <a class="p-2 text-center bg-transparent txt-danger rounded-0 item-font btneffect" style="width: 50%;" asp-route-Id="@Model.Id" asp-action="Delete"><i class="fas fa-trash"></i></a>
            </div>
        </div>
    }
</div>